# -*- coding: utf-8 -*-
"""PredPDB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z6vpKA5L1iAmBLfREbmy8VNOtDYlkY4Q

Thanks the colab example of https://github.com/dauparas/ProteinMPNN

You can design protein sequences using **ProDesign (renamded to PiFold)** from structures recorded in **pdb** files.
"""

import os
os.system("nvidia-smi")

# Add this in a Google Colab cell to install the correct version of Pytorch Geometric.
import torch

def format_pytorch_version(version):
  return version.split('+')[0]

TORCH_version = torch.__version__
TORCH = format_pytorch_version(TORCH_version)

def format_cuda_version(version):
  return 'cu' + version.replace('.', '')

CUDA_version = torch.version.cuda
CUDA = format_cuda_version(CUDA_version)

!pip install torch-scatter     -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-sparse      -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-cluster     -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-geometric

import json, time, os, sys, glob
import numpy as np

if not os.path.isdir("ProDesign"):
  os.system("git clone -q https://github.com/A4Bio/ProDesign.git")
sys.path.append('/content/ProDesign')

!mkdir -p ProDesign/results/ProDesign
!wget -O ProDesign/results/ProDesign/checkpoint.pth https://github.com/A4Bio/PiFold/releases/download/Training%26Data/checkpoint.pth

"""## Data"""

from google.colab import files
def get_pdb(pdb_code=""):
  if pdb_code is None or pdb_code == "":
    upload_dict = files.upload()
    pdb_string = upload_dict[list(upload_dict.keys())[0]]
    with open("tmp.pdb","wb") as out: out.write(pdb_string)
    return "tmp.pdb"
  else:
    os.system(f"wget -qnc https://files.rcsb.org/view/{pdb_code}.pdb")
    return f"{pdb_code}.pdb"

import os
import gzip
import numpy as np
from collections import defaultdict

AAMAP = {
    'ALA': 'A', 'ARG': 'R', 'ASN': 'N', 'ASP': 'D', 'CYS': 'C', 'GLN': 'Q',
    'GLU': 'E', 'GLY': 'G', 'HIS': 'H', 'ILE': 'I', 'LEU': 'L', 'LYS': 'K',
    'MET': 'M', 'PHE': 'F', 'PRO': 'P', 'SER': 'S', 'THR': 'T', 'TRP': 'W',
    'TYR': 'Y', 'VAL': 'V',
    'ASX': 'B', 'GLX': 'Z', 'SEC': 'U', 'PYL': 'O', 'XLE': 'J', '': '-'
}


def getSequence(resnames):
    """Returns polypeptide sequence as from list of *resnames* (residue
    name abbreviations)."""

    get = AAMAP.get
    return ''.join([get(rn, 'X') for rn in resnames])

def gzip_open(filename, *args, **kwargs):
    if args and "t" in args[0]:
        args = (args[0].replace("t", ""), ) + args[1:]
    if isinstance(filename, str):
        return gzip.open(filename, *args, **kwargs)
    else:
        return gzip.GzipFile(filename, *args, **kwargs)

def parsePDB(pdb, chain=['A']):
    title, ext = os.path.splitext(os.path.split(pdb)[1])
    title, ext = os.path.splitext(title)
    if pdb[-3:] == '.gz':
      pdb = gzip_open(pdb, 'rt')
      lines = defaultdict(list)
      for loc, line in enumerate(pdb):
          line = line.decode('ANSI_X3.4-1968')
          startswith = line[0:6]
          lines[startswith].append((loc, line))
    else:
      pdb = open(pdb)
      lines = defaultdict(list)
      for loc, line in enumerate(pdb):
          # line = line.decode('ANSI_X3.4-1968')
          startswith = line[0:6]
          lines[startswith].append((loc, line))


    pdb.close()

    sequence = ''

    CA_coords, C_coords, O_coords, N_coords = [], [], [], []

    # chain_id = []
    for idx, line in lines['ATOM  ']:
        if line[21:22].strip() not in chain:
            continue
        if line[13:16].strip() == 'CA':
            CA_coord = [float(line[30:38]), float(line[38:46]), float(line[46:54])]
            CA_coords.append(CA_coord)
            sequence += ''.join(getSequence([line[17:20]]))
        elif line[13:16].strip() == 'C':
            C_coord = [float(line[30:38]), float(line[38:46]), float(line[46:54])]
            C_coords.append(C_coord)
        elif line[13:16].strip() == 'O':
            O_coord = [float(line[30:38]), float(line[38:46]), float(line[46:54])]
            O_coords.append(O_coord)
        elif line[13:16].strip() == 'N':
            N_coord = [float(line[30:38]), float(line[38:46]), float(line[46:54])]
            N_coords.append(N_coord)



    return {'title': title,
            'seq': sequence,
            'CA': np.array(CA_coords),
            'C': np.array(C_coords),
            'O': np.array(O_coords),
            'N': np.array(N_coords),
            'score' : 100.0}

"""## Model"""

def get_parser():
  import argparse
  parser = argparse.ArgumentParser()
  # Set-up parameters
  parser.add_argument('--device', default='cuda', type=str, help='Name of device to use for tensor computations (cuda/cpu)')
  parser.add_argument('--display_step', default=10, type=int, help='Interval in batches between display of training metrics')
  parser.add_argument('--res_dir', default='ProDesign/results', type=str)
  parser.add_argument('--ex_name', default='ProDesign', type=str)
  parser.add_argument('--use_gpu', default=True, type=bool)
  parser.add_argument('--gpu', default=0, type=int)
  parser.add_argument('--seed', default=111, type=int)

  # CATH
  # dataset parameters
  parser.add_argument('--data_name', default='CATH', choices=['CATH', 'TS50'])
  parser.add_argument('--data_root', default='ProDesign/data/')
  parser.add_argument('--batch_size', default=8, type=int)
  parser.add_argument('--num_workers', default=8, type=int)

  # method parameters
  parser.add_argument('--method', default='ProDesign', choices=['ProDesign'])
  parser.add_argument('--config_file', '-c', default=None, type=str)
  parser.add_argument('--hidden_dim',  default=128, type=int)
  parser.add_argument('--node_features',  default=128, type=int)
  parser.add_argument('--edge_features',  default=128, type=int)
  parser.add_argument('--k_neighbors',  default=30, type=int)
  parser.add_argument('--dropout',  default=0.1, type=int)
  parser.add_argument('--num_encoder_layers', default=10, type=int)

  # Training parameters
  parser.add_argument('--epoch', default=100, type=int, help='end epoch')
  parser.add_argument('--log_step', default=1, type=int)
  parser.add_argument('--lr', default=0.001, type=float, help='Learning rate')
  parser.add_argument('--patience', default=100, type=int)

  # ProDesign parameters
  parser.add_argument('--updating_edges', default=4, type=int)
  parser.add_argument('--node_dist', default=1, type=int)
  parser.add_argument('--node_angle', default=1, type=int)
  parser.add_argument('--node_direct', default=1, type=int)
  parser.add_argument('--edge_dist', default=1, type=int)
  parser.add_argument('--edge_angle', default=1, type=int)
  parser.add_argument('--edge_direct', default=1, type=int)
  parser.add_argument('--virtual_num', default=3, type=int)
  args = parser.parse_args([])
  return args

import torch
from ProDesign.main import Exp
from ProDesign.parser import create_parser
args = get_parser()
exp = Exp(args)
svpath = 'ProDesign/results/ProDesign/'
exp.method.model.load_state_dict(torch.load(svpath+'checkpoint.pth'))

"""## Design"""

exp.method.model.encoder.encoder_layers[0]

exp.method.model

import torch.nn.functional as F
from ProDesign.API.dataloader_gtrans import featurize_GTrans
from ProDesign.methods.utils import cuda

pdb_name = get_pdb('2giy')
data = parsePDB('/content/{}'.format(pdb_name), ['A'])

with torch.no_grad():
  alphabet='ACDEFGHIKLMNPQRSTVWY'
  batch = featurize_GTrans([data])
  X, S, score, mask, lengths = cuda(batch, device = exp.device)
  X, S, score, h_V, h_E, E_idx, batch_id, mask_bw, mask_fw, decoding_order = exp.method.model._get_features(S, score, X=X, mask=mask)
  log_probs, logits = exp.method.model(h_V, h_E, E_idx, batch_id, return_logit = True)

  temperature = 0.1
  probs = F.softmax(logits/temperature, dim=-1)
  S_pred = torch.multinomial(probs, 1).view(-1)

recovery = torch.mean((S==S_pred).float())
S_design = ''.join([alphabet[i] for i in S_pred])
S_true = data['seq']

line = '>{}, recovery={} \n designed_chains=\n{} \n native_chains=\n{}\n'.format(pdb_name, recovery, S_design, S_true)

print(line)

data['seq']

S_design

confidence = probs.max(dim=1)[0]

cmp = np.array([one for one in data['seq']]) == np.array([one for one in S_design])
cmp = torch.tensor(cmp).cuda().float()

range14 = confidence==1.0
range13 = (0.999<=confidence)&(confidence<1.0)
range12 = (0.995<=confidence)&(confidence<0.999)
range11 = (0.99<=confidence)&(confidence<0.995)
range10 = (0.95<=confidence)&(confidence<0.99)
range9 = (0.9<=confidence)&(confidence<0.95)
range8 = (0.8<=confidence)&(confidence<0.9)
range7 = (0.7<=confidence)&(confidence<0.8)
range6 = (0.6<=confidence)&(confidence<0.7)
range5 = (0.5<=confidence)&(confidence<0.6)
range4 = (0.4<=confidence)&(confidence<0.5)
range3 = (0.3<=confidence)&(confidence<0.4)
range2 = (0.2<=confidence)&(confidence<0.3)
range1 = (0.1<=confidence)&(confidence<0.2)
range0 = (0<=confidence)&(confidence<0.1)

print(cmp[range0].mean(), range0.sum())
print(cmp[range1].mean(), range1.sum())
print(cmp[range2].mean(), range2.sum())
print(cmp[range3].mean(), range3.sum())
print(cmp[range4].mean(), range4.sum())
print(cmp[range5].mean(), range5.sum())
print(cmp[range6].mean(), range6.sum())
print(cmp[range7].mean(), range7.sum())
print(cmp[range8].mean(), range8.sum())
print(cmp[range9].mean(), range9.sum())
print(cmp[range10].mean(), range10.sum())
print(cmp[range11].mean(), range11.sum())
print(cmp[range12].mean(), range12.sum())
print(cmp[range13].mean(), range13.sum())
print(cmp[range14].mean(), range14.sum())

prompt = []
for residue, cmp2 in zip(S_design,range14):
  if cmp2:
    prompt.append(residue)
  else:
    prompt.append('<mask>')
print("".join(prompt))

data['seq']

S_design

confidence

refine_seq ="MPPGVEVTMTGPSTITFAPGETFTTPVTITAPAHDPSNYTMTVNWLPYPVPASCPAMYTPEACLANPTLPECTDPANSPCAAATWPPCLASIPYPGCSRANPPPGCRPTAPIPPPPGLSVVGNSTNLTFTNASPAHSGLYRLEVTVNGGIKAGGYVNISTPVTVKVAVVVRPGNPGGIG"

cmp2 = np.array([one for one in data['seq']]) == np.array([one for one in refine_seq])

cmp2 = torch.tensor(cmp2).cuda().float()
cmp2[range13] = cmp[range13]
cmp2.mean()

confidence

cmp

cmp2

import torch.nn.functional as F
from ProDesign.API.dataloader_gtrans import featurize_GTrans
from ProDesign.methods.utils import cuda

pdb_name = get_pdb('1mgr')
data = parsePDB('/content/{}'.format(pdb_name), ['A'])

with torch.no_grad():
  alphabet='ACDEFGHIKLMNPQRSTVWY'
  batch = featurize_GTrans([data])
  X, S, score, mask, lengths = cuda(batch, device = exp.device)
  X, S, score, h_V, h_E, E_idx, batch_id, mask_bw, mask_fw, decoding_order = exp.method.model._get_features(S, score, X=X, mask=mask)
  log_probs, logits = exp.method.model(h_V, h_E, E_idx, batch_id, return_logit = True)

  temperature = 0.1
  probs = F.softmax(logits/temperature, dim=-1)
  S_pred = torch.multinomial(probs, 1).view(-1)

recovery = torch.mean((S==S_pred).float())
S_design = ''.join([alphabet[i] for i in S_pred])
S_true = data['seq']

line = '>{}, recovery={} \n designed_chains=\n{} \n native_chains=\n{}\n'.format(pdb_name, recovery, S_design, S_true)

print(line)

import torch.nn.functional as F
from ProDesign.API.dataloader_gtrans import featurize_GTrans
from ProDesign.methods.utils import cuda

pdb_name = get_pdb('3tld')
data = parsePDB('/content/{}'.format(pdb_name), ['A'])

with torch.no_grad():
  alphabet='ACDEFGHIKLMNPQRSTVWY'
  batch = featurize_GTrans([data])
  X, S, score, mask, lengths = cuda(batch, device = exp.device)
  X, S, score, h_V, h_E, E_idx, batch_id, mask_bw, mask_fw, decoding_order = exp.method.model._get_features(S, score, X=X, mask=mask)
  log_probs, logits = exp.method.model(h_V, h_E, E_idx, batch_id, return_logit = True)

  temperature = 0.1
  probs = F.softmax(logits/temperature, dim=-1)
  S_pred = torch.multinomial(probs, 1).view(-1)

recovery = torch.mean((S==S_pred).float())
S_design = ''.join([alphabet[i] for i in S_pred])
S_true = data['seq']

line = '>{}, recovery={} \n designed_chains=\n{} \n native_chains=\n{}\n'.format(pdb_name, recovery, S_design, S_true)

print(line)